server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.193.100:3307/blog-extension?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

    druid:
      filters: stat,wall,slf4j
      aop-patterns: com.whut.zcc.sadmin.*
      stat-view-servlet: # 配置监控页
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
      web-stat-filter: # 监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter: # 详细配置
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            #不拦截更新操作
            update-allow: true
            # 拦截删表操作
            drop-table-allow: false



  redis:
    host: 139.196.193.100
    port: 6380
    timeout: 1000
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

#debug: true

#eureka:
#  client:
#    register-with-eureka: true #是否将自己注册到eureka中
#    fetch-registry: true #是否从eureka中获取信息
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true